# Azure Pipelines
# Build and deploy Virtual Library API to Azure
# https://learn.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
  # Azure service connection name - CREATE THIS in Azure DevOps > Project Settings > Service Connections
  azureServiceConnection: 'azure-service-connection'  # CHANGE THIS to your service connection name
  dockerRegistryServiceConnection: 'virtuallibraryacr'
  imageRepository: 'virtual-library-api'
  containerRegistry: 'virtuallibraryacr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'
  resourceGroupName: 'biblioteca'
  location: 'canadacentral'

stages:
  - stage: DeployInfrastructure
    displayName: Deploy Infrastructure
    jobs:
      - job: DeployBicep
        displayName: Deploy Bicep Template
        pool:
          vmImage: $(vmImageName)
        steps:
          - checkout: self

          - task: AzureResourceGroupDeployment@2
            displayName: Deploy Bicep Infrastructure
            inputs:
              azureSubscription: $(azureServiceConnection)
              action: 'Create Or Update Resource Group'
              resourceGroupName: $(resourceGroupName)
              location: $(location)
              templateLocation: 'Linked artifact'
              csmFile: '$(Build.SourcesDirectory)/infrastructure/main.bicep'
              csmParametersFile: '$(Build.SourcesDirectory)/infrastructure/parameters.json'
              deploymentMode: 'Incremental'
              deploymentName: 'virtual-library-infra-$(Build.BuildId)'

  - stage: Build
    displayName: Build and push stage
    dependsOn: DeployInfrastructure
    condition: succeeded()
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - checkout: self

          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: $(dockerRegistryServiceConnection)

          - task: Docker@2
            displayName: Build image
            inputs:
              command: build
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest

          - task: Docker@2
            displayName: Push image to ACR
            inputs:
              command: push
              repository: $(imageRepository)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest

  - stage: Deploy
    displayName: Deploy to Web App
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: Deploy
        displayName: Deploy
        pool:
          vmImage: $(vmImageName)
        steps:
          - checkout: none

          - task: AzureCLI@2
            displayName: Get Web App Name
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Get the web app name from the resource group
                webAppName=$(az webapp list --resource-group $(resourceGroupName) --query "[0].name" -o tsv)
                echo "Web App Name: $webAppName"
                echo "##vso[task.setvariable variable=webAppName]$webAppName"

          - task: AzureWebAppContainer@1
            displayName: Deploy to App Service
            inputs:
              azureSubscription: $(azureServiceConnection)
              appName: $(webAppName)
              containers: $(containerRegistry)/$(imageRepository):$(tag)
              startUpCommand: ''
